In [1]:
import numpy as np

def realign_matrix(M, dA, dB):
    """
    Realigns an (dA*dB) x (dA*dB) matrix into (dA^2) x (dB^2).
    
    Parameters:
    M (numpy.ndarray): The input (dA*dB) x (dA*dB) matrix.
    dA (int): Dimension of subsystem A.
    dB (int): Dimension of subsystem B.
    
    Returns:
    numpy.ndarray: The realigned matrix.
    """
    # Reshape the matrix into a 4D tensor
    M_tensor = M.reshape(dA, dB, dA, dB)
    
    # Transpose and reshape into the realigned matrix
    M_realigned = M_tensor.transpose(0, 2, 1, 3).reshape(dA**2, dB**2)
    
    return M_realigned

# Example: 8x8 random matrix
np.random.seed(42)
M = np.random.rand(8, 8)  # Example random 8x8 matrix

# Realign for a (4x2) system
realigned_M = realign_matrix(M, 4, 2)

print("Original Matrix (8x8):\n", M)
print("\nRealigned Matrix (16x4):\n", realigned_M)


Original Matrix (8x8):
 [[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
  0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985 0.83244264 0.21233911
  0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914 0.61185289 0.13949386
  0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041
  0.60754485 0.17052412]
 [0.06505159 0.94888554 0.96563203 0.80839735 0.30461377 0.09767211
  0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204  0.25877998 0.66252228
  0.31171108 0.52006802]
 [0.54671028 0.18485446 0.96958463 0.77513282 0.93949894 0.89482735
  0.59789998 0.92187424]
 [0.0884925  0.19598286 0.04522729 0.32533033 0.38867729 0.27134903
  0.82873751 0.35675333]]

Realigned Matrix (16x4):
 [[0.37454012 0.95071431 0.60111501 0.70807258]
 [0.73199394 0.59865848 0.02058449 0.96990985]
 [0.15601864 0.15599452 0.83244264 0.21233911]
 [0.05808361 0.86617615 0.18182497 0.18340451]
 [0.30424224 0.5

In [46]:
import numpy as np

def realign_matrix(M, dA, dB):
    """
    Computes the realigned matrix R_2 for an (dA*dB) x (dA*dB) matrix.

    Parameters:
    M (numpy.ndarray): The input (dA*dB) x (dA*dB) matrix.
    dA (int): Dimension of subsystem A.
    dB (int): Dimension of subsystem B.

    Returns:
    numpy.ndarray: The realigned matrix.
    """
    # Reshape into a 4D tensor
    M_tensor = M.reshape(dA, dB, dA, dB)
    
    # Transpose and reshape to obtain the realigned matrix
    M_realigned = M_tensor.transpose(0, 2, 1, 3).reshape(dA**2, dB**2)
    
    return M_realigned

# Toffoli Gate (CCNOT) 8x8 matrix
# Toffoli = np.array([
#     [1, 0, 0, 0, 0, 0, 0, 0],
#     [0, 1, 0, 0, 0, 0, 0, 0],
#     [0, 0, 1, 0, 0, 0, 0, 0],
#     [0, 0, 0, 1, 0, 0, 0, 0],
#     [0, 0, 0, 0, 1, 0, 0, 0],
#     [0, 0, 0, 0, 0, 1, 0, 0],
#     [0, 0, 0, 0, 0, 0, 0, 1],
#     [0, 0, 0, 0, 0, 0, 1, 0]
# ])

Toffoli= np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                     [0, 1, 0, 0, 0, 0, 0, 0],
                     [0, 0, 1, 0, 0, 0, 0, 0],
                     [0, 0, 0, 1, 0, 0, 0, 0],
                     [0, 0, 0, 0, 1, 0, 0, 0],
                     [0, 0, 0, 0, 0, 1, 0, 0],
                     [0, 0, 0, 0, 0, 0, 0, 1],
                     [0, 0, 0, 0, 0, 0, 1, 0]])

# Compute the realigned matrix R_2
R2_Toffoli = realign_matrix(Toffoli, 4, 2)

print("Realigned Matrix R_2 for Toffoli Gate:\n", R2_Toffoli)

singular_values = np.linalg.svd(R2_Toffoli, compute_uv=False)
print("Singular Values of R_2:", singular_values)
# Compute the full SVD decomposition of R_2
U, S, Vh = np.linalg.svd(R2_Toffoli)

# Extract the three matrices U, S (as a diagonal matrix), and Vh
Sigma = np.zeros_like(R2_Toffoli, dtype=float)
np.fill_diagonal(Sigma, S)  # Convert singular values into diagonal matrix

# Output the matrices
U, Sigma, Vh

# Print the dimensions of the matrices
# U_shape = U.shape
# Sigma_shape = Sigma.shape
# Vh_shape = Vh.shape

# U_shape, Sigma_shape, Vh_shape




Realigned Matrix R_2 for Toffoli Gate:
 [[1 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 1 0]]
Singular Values of R_2: [2.44948974 1.41421356 0.         0.        ]


(array([[-0.57735027,  0.        ,  0.        ,  0.        ,  0.        ,
         -0.57735027,  0.        ,  0.        ,  0.        ,  0.        ,
         -0.57735027,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         -1.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.        

In [73]:
import numpy as np

def multiply_matrices(A, B, C):
    """
    Multiplies three matrices A, B, and C in order.
    
    Parameters:
    A (numpy.ndarray): First matrix.
    B (numpy.ndarray): Second matrix.
    C (numpy.ndarray): Third matrix.
    
    Returns:
    numpy.ndarray: The result of A * B * C.
    """
    # Check if dimensions match for multiplication
    if A.shape[1] != B.shape[0]:
        raise ValueError("Matrix A columns must match Matrix B rows")
    if B.shape[1] != C.shape[0]:
        raise ValueError("Matrix B columns must match Matrix C rows")
    
    # Perform matrix multiplication
    result = np.dot(np.dot(A, B), C)
    return result

def conjugate_transpose(matrix):
    """
    Computes the conjugate transpose (Hermitian transpose) of a matrix.
    
    Parameters:
    matrix (numpy.ndarray): Input matrix.
    
    Returns:
    numpy.ndarray: Conjugate transpose of the input matrix.
    """
    return np.conjugate(matrix).T

def realign_matrix(M, dA, dB):
    """
    Computes the realigned matrix R_2 for an (dA*dB) x (dA*dB) matrix.

    Parameters:
    M (numpy.ndarray): The input (dA*dB) x (dA*dB) matrix.
    dA (int): Dimension of subsystem A.
    dB (int): Dimension of subsystem B.

    Returns:
    numpy.ndarray: The realigned matrix.
    """
    # Reshape into a 4D tensor
    M_tensor = M.reshape(dA, dB, dA, dB)
    
    # Transpose and reshape to obtain the realigned matrix
    M_realigned = M_tensor.transpose(0, 2, 1, 3).reshape(dA**2, dB**2)
    
    return M_realigned
def eigenvalues_and_eigenvectors(matrix):
    """
    Computes and prints the eigenvalues and corresponding eigenvectors of a matrix.
    
    Parameters:
    matrix (numpy.ndarray): Input square matrix.
    
    Returns:
    None
    """
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Matrix must be square")
    
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    print("Eigenvalues:", eigenvalues)
    print("Eigenvectors:")
    print(eigenvectors)

A=np.array([[0,1],[1,0]])
B=np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])

C=np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                     [0, 1, 0, 0, 0, 0, 0, 0],
                     [0, 0, 1, 0, 0, 0, 0, 0],
                     [0, 0, 0, 1, 0, 0, 0, 0],
                     [0, 0, 0, 0, 1, 0, 0, 0],
                     [0, 0, 0, 0, 0, 1, 0, 0],
                     [0, 0, 0, 0, 0, 0, 0, 1],
                     [0, 0, 0, 0, 0, 0, 1, 0]])


D=realign_matrix(C,2,4)
print(D)


D_d=conjugate_transpose(D)
DD_d=np.dot(D,D_d)
D_dD=np.dot(D_d,D)

eigenvalues, eigenvectors = np.linalg.eig(D_dD)

# Print results
print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)



[[1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0]]
Eigenvalues:
[-4.44089210e-16+0.00000000e+00j  6.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j  2.00000000e+00+0.00000000e+00j
 -2.04677589e-17+4.92900858e-17j -2.04677589e-17-4.92900858e-17j
  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]
Eigenvectors:
[[-8.16496581e-01+0.j          5.77350269e-01+0.j
   4.31685849e-01+0.j         -2.81198996e-17+0.j
  -2.16731782e-01-0.10502648j -2.16731782e-01+0.10502648j
   0.00000000e+00+0.j          0.00000000e+00+0.j
   0.00000000e+00+0.j          0.00000000e+00+0.j
   0.00000000e+00+0.j          0.00000000e+00+0.j
   

In [71]:
A=np.array([[0.5,0,0,0],[0,0.5,0,0],[0,0,0.2,0.2],[0,0,0.2,0.2]])
B=np.array([[0,0,0,0],[0,0,0,0],[0,0,0.5,-0.5],[0,0,-0.5,0.5]])
C=np.array([[0.707,0],[0,0.707]])
D=np.array([[-0.707,0],[0,0.707]])
H=6*np.kron(C,A)+2*np.kron(D,B
                           )
print(H)

[[2.121  0.     0.     0.     0.     0.     0.     0.    ]
 [0.     2.121  0.     0.     0.     0.     0.     0.    ]
 [0.     0.     0.1414 1.5554 0.     0.     0.     0.    ]
 [0.     0.     1.5554 0.1414 0.     0.     0.     0.    ]
 [0.     0.     0.     0.     2.121  0.     0.     0.    ]
 [0.     0.     0.     0.     0.     2.121  0.     0.    ]
 [0.     0.     0.     0.     0.     0.     1.5554 0.1414]
 [0.     0.     0.     0.     0.     0.     0.1414 1.5554]]
